name: PR Commit Messages

on:
  pull_request:
    types: [opened, synchronize, reopened] # Trigger on PR opened, synchronized, or reopened

jobs:
  get-pr-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch all commit history
        run: |
          git fetch --prune --unshallow

      - name: Get commit messages for all commits in PR
        id: get_all_commit_messages
        run: |
          # Get all commit messages in the PR branch
          COMMIT_MESSAGES=$(git log --format=%s ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          echo "$COMMIT_MESSAGES" >> $GITHUB_ENV

      - name: Output all commit messages
        run: |
          echo "All commit messages in the PR: ${{ env.COMMIT_MESSAGES }}"
